language: python
python:
  - "3.9"
  - "3.10"
install:
  - pip install flake8 yapf
  - python setup.py install
script:
  - aws_close_account --help
  - flake8 aws_close_account
  - yapf -d -r aws_close_account/
